### ISSUE TITLE
Measure memcpy performance impact for the PV DRM implementation.

### ISSUE THREAD

**Issue by aanisov** [xen-troops/displ_be#1]
Memcpy impact on PV DRM performance should be measured following this discussion:
https://lists.xenproject.org/archives/html/xen-devel/2016-11/msg01298.html

**Comment by rshym** [comment]
I do not know who is waiting for results of this measurement, and at this point I'm afraid to ask, taking into account that issue has no updates from Dec 5, 2016. :)
