### ISSUE TITLE
Virtual Console

### ISSUE THREAD

**Issue by ska67** [xen-troops/displ_be#135]
I use your displ_be for graphical output from PV and PVH domains. I use it to run some domU with full desktop environment. Both in Wayland mode and with DRM. Great software, thanks!

I have not yet succeeded in displaying the virtual console. And the output of the boot messages even less.
Is that even possible?

**Comment by lorc** [comment]
Hi Stefan,

Well, I'm not sure that we even tried to use virtual console with PV DRM driver. As far as I know, virtual console uses old framebuffer API, while PV DRM provides only DRM interface. I vaguely remember that DRM framework had some wrapper for framebuffer calls. But I'm not 100% sure.

I believe, @andr2000  can provide more information.

**Comment by andr2000** [comment]
Yes, we do not support framebuffer and unfortunately there is no plan to add that

**Comment by ska67** [comment]
Thank you very much for your responses, you have helped me a lot.

I installed kmscon, which uses DRM, and was able to access virtual consoles, both in DRM and WAYLAND mode.
That's all I need, perfect.
