### ISSUE TITLE
Get rid of deprecated wl_shell protocol

### ISSUE THREAD

**Issue by rshym** [xen-troops/displ_be#148]
> wl_shell is considered as deprecated across the entire Wayland community, with new clients being designed to use the new xdg_shell protocol.

It still possible to work with ws_shell using `EXTRA_OEMESON:append = " -Ddeprecated-wl-shell=true"` but quite possible that this workaround will be not available in further versions of weston

**Comment by arminn** [comment]
https://github.com/xen-troops/displ_be/pull/149
