### ISSUE TITLE
kbdfront rings must be handled differently

### ISSUE THREAD

**Issue by andr2000** [xen-troops/displ_be#18]
Scenario:
1. Start BE
2. Start FE
3. Stop BE
4. Start BE
29.06.17 09:57:38.223 | RingBuffer      | DBG - Send event, port: 13, prod: 0, cons: 2139, num events: 51
**prod: 0, cons: 2139**
In this scenario care must be taken of the state machine of xen_kbdfront which initializes ring buffer once at the first start, e.g. its state machine doesn't see that BE has recycled.
This makes it stuck on the very first event from BE, because cons > prod and it tries to read all the events until its cons wraps and matches prod. This renders guest machine unusable

Fix could be for the BE to read cons at start and set prod = cons

**Comment by al1img** [comment]
Fixed in 9896635210e769d7a29f0285ca9138bac098be77
