### ISSUE TITLE
Display Manager on backend side

### ISSUE THREAD

**Issue by al1img** [xen-troops/displ_be#2]
Implement Display Manager which will handle surfaces from display backend and other applications.
- display backend and applications create surfaces with unique surface id;
- display manager arrange all surfaces based on surface id and global display policies;
- check GENIVI/wayland-ivi-extension LayerManagerControl as main solution.

**Comment by klogg** [comment]
![display](https://cloud.githubusercontent.com/assets/598982/24450751/b23325f0-1484-11e7-8287-df55b810ec15.png)

**Comment by al1img** [comment]
In addition, investigate following input cases:
- 2 displays, 2 touch screens;
- input device hot plug;

![img_0322](https://cloud.githubusercontent.com/assets/6860363/24453009/c675bd66-148e-11e7-9812-035d8130f874.JPG)

**Comment by klogg** [comment]
https://at.projects.genivi.org/wiki/display/PROJ/IVI+Layer+Management

**Comment by rshym** [comment]
Is Display Manager implemented yet?

**Comment by rshym** [comment]
Closed after discussion with author.
