### ISSUE TITLE
onUp event is only reported once

### ISSUE THREAD

**Issue by andr2000** [xen-troops/displ_be#20]
For multi touch device onUp event is only reported for the very first id in series, e.g. for 2 fingers:
onUp id=0 and no id=1.
Workaround:

diff --git a/src/displayBackend/wayland/SeatTouch.cpp b/src/displayBackend/wayland/SeatTouch.cpp
index 01965d2be68a..c47580440867 100644
--- a/src/displayBackend/wayland/SeatTouch.cpp
+++ b/src/displayBackend/wayland/SeatTouch.cpp
@@ -117,7 +117,7 @@ void SeatTouch::onUp(uint32_t serial, uint32_t time, int32_t id)
                }
        }
 
-       mCurrentCallback = mCallbacks.end();
+//     mCurrentCallback = mCallbacks.end();
 }

**Comment by al1img** [comment]
Fixed in d6efcff275678aa331fc18ecdbd99af79bcd0658
