### ISSUE TITLE
Investigate different input cases

### ISSUE THREAD

**Issue by al1img** [xen-troops/displ_be#3]
Investigate following input cases:
- 2 displays, 2 touch screens;
- input device hot plug;

![img_0322](https://cloud.githubusercontent.com/assets/6860363/24455010/c8d1617a-1496-11e7-81b0-3498c8cd8026.JPG)

**Comment by rshym** [comment]
Seems we already not only investigated, but also implemented "2 displays, 2 touch screens".
But I'm not sure regarding hotplug of input.

**Comment by rshym** [comment]
Closed after discussion with author.
