### ISSUE TITLE
Implement Android ion buffers case

### ISSUE THREAD

**Issue by al1img** [xen-troops/displ_be#33]
We've agreed that for this special case the scenario should be as following:

- to identify this case BE will receive create dbuf req with w = h = 0;
- BE doesn't create dbuf but stores refs (or buffer?) in map associated with dbuf cookie;
- on fbuf create req BE checks dbuf cookie is it already created or not. If it is not created BE creates dbuf with previously stored refs (or buffer)  and w, h, same as for fbuf but bpp should be calculated from pixel format.
- on dbuf delete req: BE should delete the dbuf.

**Comment by al1img** [comment]
Done

**Comment by aanisov** [comment]
@al1img, please reference PR or commit addresses this issue.
