### ISSUE TITLE
Segmentation fault on Ctrl+C

### ISSUE THREAD

**Issue by al1img** [xen-troops/displ_be#7]
displ_be -c ../displ_be.cfg
ivi_controller not available
[Warning] The ilm_control_context is already destroyed
01.01.70 00:03:27.549 | Display | WRN - Can't initialize ILM: failed. ILM capability will be disabled.
01.01.70 00:03:27.557 | DisplBackend | INF - Create new frontend: Dom(1/0)
01.01.70 00:03:27.558 | DisplFrontend | INF - Dom(1/0) Set backend state to: [Initializing]
01.01.70 00:03:27.560 | DisplFrontend | INF - Dom(1/0) Frontend state changed to: [Initializing]
01.01.70 00:03:27.560 | DisplFrontend | INF - Dom(1/0) Set backend state to: [InitWait]
01.01.70 00:03:27.576 | DisplFrontend | INF - Dom(1/0) Frontend state changed to: [Initialized]
01.01.70 00:03:27.577 | DisplFrontend | INF - Dom(1/0) Add ring buffer, ref: 2476, port: 20
01.01.70 00:03:27.579 | DisplFrontend | INF - Dom(1/0) Add ring buffer, ref: 2475, port: 19
01.01.70 00:03:27.580 | DisplFrontend | INF - Dom(1/0) Set backend state to: [Connected]
01.01.70 00:03:27.599 | DisplFrontend | INF - Dom(1/0) Frontend state changed to: [Connected]
^C01.01.70 00:11:15.003 | DisplFrontend | INF - Dom(1/0) Set backend state to: [Closing]
01.01.70 00:11:15.079 | Main          | ERR - Segmentation fault!
displ_be(_Z19segmentationHandleri+0x74)[0x4298b4]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffffb73866c0]
displ_be(_ZN21DisplayCommandHandler13sendFlipEventEm+0x224)[0x436ce4]
displ_be(_ZN7Wayland7Surface12frameHandlerEv+0x13c)[0x45ea8c]
/usr/lib/libffi.so.6(ffi_call_SYSV+0x64)[0xffffb6d8de14]
/usr/lib/libffi.so.6(ffi_call+0x9c)[0xffffb6d8e73c]
/usr/lib/libwayland-client.so.0(+0x8c08)[0xffffb7282c08]

**Comment by al1img** [comment]
configuration:

// Display section describes display backend settings
display:
{
    // Indicates which graphics system shall be used:
    // if true - wayland, otherwise DRM.
    useWayland = true;
    
    // Describes domain's configuration.
    // name - domain name;
    // devId - device id;
    // connectors - array of backend connector names which corresponds frontend
    // connector indexes. For wayland these names are virtual connectors
    // described in wayland section below. For DRM these are hardware DRM
    // connectors.
    doms = (
        { name = "DomU"; devId = 0; connectors = ["HDMI-A-1", "HDMI-B-0", "VGA"]; }
    );
    wayland:
    {
        // Optional setting.
        // Used when there is no IVI extension.
        // Creates background surface and other surfaces (connectors) will
        // be created related to this one.
        background = { w = 1920; h = 1080; };
        //background = { w = 1024; h = 768; };
        
        // Describes wayland virtual connectors.
        // This section is relevant in case wayland = true.
        // id - connector id to identify virtual connector (used in connectors
        // array above);
        // screen - wayland screen id on which this connector should be
        // assigned (if omitted, 0 is used);
        // x - horizontal offset;
        // y - vertical offset;
        // w - width;
        // h - height;
        // z - Z order (if omitted, 0 is used);
        connectors = (
            { name = "HDMI-A-1"; screen = 0; x = 0; y = 0; w = 320; h = 240; z = 10; },
            { name = "Second"; screen = 1; x = 320; y = 0; w = 320; h = 240; z = 100; },
            { name = "Third"; x = 320; y = 0; w = 320; h = 240; }
        );
    }
};

**Comment by al1img** [comment]
Done

**Comment by aanisov** [comment]
@al1img, please reference PR or commit addresses this issue.
