### ISSUE TITLE
Generate crash dump on segmentation fault

### ISSUE THREAD

**Issue by al1img** [xen-troops/displ_be#71]
Because backend overrides default segmentation fault handler, crash dumb is not generated.
To keep both handlers following solution could be applied:

http://www.alexonlinux.com/how-to-handle-sigsegv-but-also-generate-core-dump

**Comment by lorc** [comment]
According to discussion in comments for this post, this approach is not reliable:
http://www.alexonlinux.com/how-to-handle-sigsegv-but-also-generate-core-dump#comment-34463

I think, we need to find a proper way to do this.

**Comment by al1img** [comment]
Thanks @lorc  to point it out. I rework it by using SA_RESETHAND flag to restore default handler and use raise to resend SIGSEGV. See PR https://github.com/xen-troops/displ_be/pull/74

**Comment by al1img** [comment]
Close with PR #74.
