### ISSUE TITLE
On deleting DomU and active backend there is zomby domain

### ISSUE THREAD

**Issue by al1img** [xen-troops/displ_be#8]
xl destroy 1
[   87.949763] xenbr0: port 2(vif1.0) entered disabled state
[   88.015029] xenbr0: port 2(vif1.0) entered disabled state
[   88.022057] device vif1.0 left promiscuous mode
[   88.026714] audit: type=1700 audit(87.575:4): dev=vif1.0 prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295
[   88.037574] xenbr0: port 2(vif1.0) entered disabled state
root@m3ulcb-xen-dom0:~/xen-scripts#
root@m3ulcb-xen-dom0:~/xen-scripts#
root@m3ulcb-xen-dom0:~/xen-scripts# xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0   512     4     r-----      18.8
(null)                                       1     0     4     --p--d       5.8
root@m3ulcb-xen-dom0:~/xen-scripts#
root@m3ulcb-xen-dom0:~/xen-scripts# xenstore-ls -f
/tool = ""
/tool/xenstored = ""
/local = ""
/local/domain = ""
/local/domain/0 = ""
/local/domain/0/control = ""
/local/domain/0/control/feature-poweroff = "1"
/local/domain/0/control/feature-reboot = "1"
/local/domain/0/domid = "0"
/local/domain/0/name = "Domain-0"
/local/domain/0/backend = ""
/local/domain/0/backend/vdispl = ""
/local/domain/0/backend/vdispl/1 = ""
/local/domain/0/backend/vdispl/1/0 = ""
/local/domain/0/backend/vdispl/1/0/versions = "1"
/local/domain/0/backend/vdispl/1/0/frontend-id = "1"
/local/domain/0/backend/vdispl/1/0/frontend = "/local/domain/1/device/vdispl/0"
/local/domain/0/backend/vdispl/1/0/state = "4"
/vm = ""
/libxl = ""

**Comment by al1img** [comment]
Done

**Comment by aanisov** [comment]
@al1img, please reference PR or commit addresses this issue.
